name: Vendoora Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install || yarn install || echo "No package manager detected"
      - name: Firebase or Vercel Deploy
        run: echo "⚙️ Trigger your manual deploy here"
